### ISSUE TITLE
Generate Liam3 with new APMS

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/liam3#6]

**Comment by AnaMickovic** [comment]
@bilievskissi : can you please add the no of hours for this task - missed it yesterday... thx!

**Comment by AnaMickovic** [comment]
Hello Daniel, Hello Boban,

can you please update on status of this task?
Also the time needed.

Thank you
Ana

**Comment by dwu300** [comment]
Time would probably be in case of success 1h
